apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-deletetask
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name}}-deletetask
  ports:
  - port: {{ .Values.deletetask.servicePort }}
    targetPort: {{ .Values.deletetask.port }}
