apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-deletetask
spec:
  selector:
    app: {{ .Release.Name}}-deletetask
  ports:
  - port: {{ .Values.deletetask.service.port }}
    targetPort: {{ .Values.deletetask.service.targetPort }}
