apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-addtask-ingress
  labels:
    app.kubernetes.io/name: addtask-ingress
spec:
  ingressClassName: {{ .Values.common.ingressClassName }}
  rules:
  - host: {{ .Values.addtask.ingress.host}}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Release.Name }}-addtask
            port: 
              number: {{ .Values.addtask.port}}
