apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-addtask
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name}}-addtask
  ports:
  - port: {{ .Values.addtask.servicePort }}
    targetPort: {{ .Values.addtask.port }}
