apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-addtask
spec:
  selector:
    app: {{ .Release.Name}}-addtask
  ports:
  - port: {{ .Values.addtask.service.port }}
    targetPort: {{ .Values.addtask.service.targetPort }}
