apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-microtodoui
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-microtodoui
  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: {{ .Values.ui.service.targetPort }}

    
