apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gettask
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-gettask
  ports:
  - port: {{ .Values.gettask.service.port }}
    targetPort: {{ .Values.gettask.service.targetPort }}